// Code generated by protoc-gen-go. DO NOT EDIT.
// source: micro_store

/*
Package micro_store is a generated protocol buffer package.

It is generated from these files:
	micro_store

It has these top-level messages:
*/
package micro_store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("micro_store", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 37 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4c, 0x2e,
	0xca, 0x8f, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x05, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x72, 0xc3,
	0xc0, 0x0d, 0x00, 0x00, 0x00,
}
